### ISSUE TITLE
When will the code for this paper be provided?

### ISSUE THREAD

**Issue by CharlesChen24** [Natyren/MixedAE#1]
I'm very interested in your this work, so when will the code for this paper be provided?

**Comment by Natyren** [comment]
@CharlesChen24 Thank you very much for your interest! I've been a bit busy lately, but I plan to upload the main code within the next two weeks.

**Comment by Natyren** [comment]
Hello @CharlesChen24 , the code is ready, you can use the model now. Next, I plan to catch bugs and add code for pretraining and model weight transfer to ViT for inference and finetune.
