### ISSUE TITLE
mixing don’t change the shape？

### ISSUE THREAD

**Issue by Murasame-sway** [Natyren/MixedAE#2]
Hello, I have reviewed the code you provided and I hope you can provide some guidance on the parts that I have some doubts about. 
In the mixing function, four images‘ patches  are passed in, but the shape returned  is still the same as before, and different from the image size in the paper texture where each of the four images is taken as a part to form one image size
in my opinion,[4,196,1024]should be made to[1,196,1024] like follow image.
![image](https://github.com/Natyren/MixedAE/assets/67264710/05284a14-ea5d-4cb5-84c5-54fe4450ed85)

**Comment by Natyren** [comment]
Hello @tsw123678 ! I've decided to implement the full mixing mode as specified in this example. In this case, the batch size remains unchanged.
<img width="630" alt="image" src="https://github.com/Natyren/MixedAE/assets/51296182/0a1ca3e9-6792-4852-b50a-f2136ca146c2">

**Comment by tsw123678** [comment]
year，I know！Thanks for your contribute！

**Comment by Murasame-sway** [comment]
> Hello @tsw123678 ! I've decided to implement the full mixing mode as specified in this example. In this case, the batch size remains unchanged. <img alt="image" width="630" src="https://private-user-images.githubusercontent.com/51296182/285655276-0a1ca3e9-6792-4852-b50a-f2136ca146c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMDc0MzQsIm5iZiI6MTcwMTAwNzEzNCwicGF0aCI6Ii81MTI5NjE4Mi8yODU2NTUyNzYtMGExY2EzZTktNjc5Mi00ODUyLWI1MGEtZjIxMzZjYTE0NmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDEzNTg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NThjZWY3MjM3ODUxZWYzMTIwNjYzMTM0NWY0MmY4ODg5NWZjMjYyZGE0MzZmYjdjZTJkODg4OGViODJkYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bjyBZRxnyl1g-yUx60SdWUkU374Z1Apcm7Goe7ivjVU">

year，I know！Thanks for your contribute！
