### ISSUE TITLE
code has some little issue.

### ISSUE THREAD

**Issue by Murasame-sway** [Natyren/MixedAE#3]
when I run your code,I find some questions and i had solved it.
In the function "mixing" ,a and idx are not in the same device.the problem also exists in forward_encoder

**Comment by Natyren** [comment]
Hello @tsw123678 ! Thank you for the review and interest in the implementation! Yes, unfortunately, I didn't test the code on GPU. Would you like to create a pull request?

**Comment by Murasame-sway** [comment]
> 你好@tsw123678！感谢您的审查和对实施的兴趣！是的，不幸的是，我没有在 GPU 上测试代码。您想创建拉取请求吗？

i feel lucky to join your work.By the way,when will you start train in your plan?

**Comment by Natyren** [comment]
@tsw123678 Thank you very much for the contribution! I plan to start the training as soon as I free up some resources.

**Comment by Natyren** [comment]
Close issue due to pr #4
